question_arr = [
                "How do I get patient's appetite back?",
                "How do I prevent recurring mouth sores?",
                "Standard anti-nausea meds don't seem to help, anything else?",
                "When should the patient get vaccinated for H1N1?",
                "How frequently should I be monitoring the patient's weight",
                "Patient is concerned about rising pain in sternum",
                "Patient is unable to afford food",
                "Should patient eat before next scheduled visit?",
                "Will patient be able to drive by themselves to and from next visit?",
                "Will health insurance cover next visit?",
                "Will health insurance cover next round of prescriptions?",
                "Is food available at the appointment?",
                "How long will the next visit last?",
                "Can other caregivers and loved ones be present at next visit?",
                "Is oral chemotherapy taken by itself, or with other treatments?",
                "How much grace period is there for me to take my medicine around the scheduled time?",                
                ]