#format needs to be:
#[category, body, source, responsetext1,responsefrom2,responsetype2, 
#
#
#]

#each element in the array represents one sequence of issues
interactions_arr = [
    ["question","How do I get patient's appetite back?","caregiver","I'm going to loop in a eating specialist for our next conversation.","provider","comment","Can you provide me the last few meals the patient had?","provider","comment","","",""],
    ["question","How do I prevent recurring mouth sores?","patient","There are several topical treatments you can try.  Please see http://www.emedicinehealth.com/canker_sores/article_em.htm","provider","comment","Yeah, I tried those, but they didn't seem to fit the patient's description.","caregiver","comment","Interesting.  If it persists to unbearable levels, let's schedule an appointment asap.","provider","comment"],
    ["question","Standard anti-nausea meds don't seem to help, anything else?","caregiver","Can you verify that ALL the medications for their anti nausea meds are being taken?  They are specially tailored for the nasuea side effects of the chemo they are on.  If they are taking them to the letter, then we will need to arrange an appointment to adjust their dosage.","provider","comment","Ah, ok come to think of it, the patient just told me they hadn't been taking them all in sequence.  I'll get back to you once she tries to follow them to the letter.","caregiver","comment","","",""],
    ["question","When should the patient get vaccinated for H1N1?","patient","Immediately- we have already put her on the front of the waiting queue - cancer patients are high risk for contracting the disease.","provider","Resolve","","","","","",""],
    ["question","How frequently should I be monitoring the patient's weight","caregiver","Please instruct the patient to use the home monitoring device daily.  ","provider","Resolve","","","","","",""],
    ["question","Patient is concerned about rising pain in sternum","caregiver","Let's follow this up at the next visit.  For now it's something we'll consider normal.","provider","comment","Ok.  It's been a little while later and it's come down.","caregiver","comment","","",""],
    ["question","Patient is unable to afford food","caregiver","I've given a call to meals on wheels, expect a call from them.","provider","Resolve","","","","","",""],
    ["question","Should patient eat before next scheduled visit?","caregiver","No, they should fast before the next visit","provider","Resolve","","","","","",""],
    ["question","Will patient be able to drive by themselves to and from next visit?","provider","I will be taking the patient to the visit myself","caregiver","Resolve","","","","","",""],
    ["question","Will health insurance cover next round of prescriptions?","caregiver","All medications that we provide in the clinic are covered under the patient's insurance policy","provider","Resolve","","","","","",""],
    ["question","How long will the next visit last?","caregiver","The next visit is 20 minutes clinical, 60 minute therapy.  Please plan for 2 hours.","provider","Resolve","","","","","",""],
    ["question","Can other caregivers and loved ones be present at %s's next visit?","caregiver","Yes, feel free to come.","provider","Resolve","","","","","",""],
    ["question","Is oral chemotherapy taken by itself, or with other treatments?","caregiver","If %s is able to keep food down, then by all means take with food.","provider","Resolve","","","","","",""],
    ["question","How much grace period is there for me to take my medicine around the scheduled time?","caregiver","Please try to be as prompt and regulated as possible.","provider","Resolve","","","","","",""],
    ["question","I'm noticing %s seems to be rapidly gaining weight","caregiver","Make sure %s is doing the daily home monitoring measurements, if the weight gain is that rapid, the visiting nurse will contact you.","provider","Resolve","","","","","",""],
    ["question","%s seems to be rapidly losing weight","caregiver","Make sure the %s is doing the daily home monitoring measurements, if the weight gain is that rapid, the visiting nurse will contact you.","provider","Resolve","","","","","",""],
    ["question","I'm noticing %s has trouble hearing me, is this temporary?","caregiver","If the symptoms worsen over the next 48 hours please come in immediately.","provider","Resolve","","","","","",""],
    ["question","%s's skin is going crazy, help!","caregiver","Please see the care plan on skin side effects - if the issues persist and match the high severity scenarios, please come in.","provider","comment","Yeah, I tried those, but even the ones that fit the patient's symtoms don't seem to provide any relief!","caregiver","","","",""],
    ["question","%s keeps mentioning abnormal muscle weakness, anything more I can do?  ","caregiver","Unfortunately this is a normal side effect.  There are ways to combat it to give the patient some normalcy to their routines.  Please see the care plan on fatigue management.","provider","Resolve","","","","","",""],
    ["issue","%s is complaining of shaking chills","Caregiver","If there is no fever, then this may be normal.","provider","Resolve","no fever, I think we can wait on this for a bit","caregiver","","","",""],
    ["issue","Patient is experiencing bleeding or bruising","Caregiver","Let's see how they heal in the next few days, if they persist, I will examine at the next visit, so long as they don't spread and get bigger, if that's the case come in immediately.","provider","Resolve","","","","","",""],
    ["issue","%s has severe constipation or diarrhea","Caregiver","Please see the updated care plan on GI issues.","provider","Resolve","","","","","",""],
    ["issue","It hurts to go to the bathroom","patient","Please see the updated care plan on GI issues.","provider","Resolve","","","","","",""],
    ["issue","%s has blood in urine or stool","Caregiver","The visiting nurse looks to be visiting in the next 24 hours, I will have them take a look.","provider","Resolve","","","","","",""],
    ["issue","Patient has soreness, redness, swelling, pus, or drainage at VAD site","Caregiver","Instructing visiting nurse to take a second look at dressings","provider","Resolve","","","","","",""],
    ["issue","Patient has irregular or rapid heart beat","Caregiver","If there is a fever, then call 911.","provider","Resolve","","","","","",""],
    ["issue","Patient has pain that is not relieved by prescribed pain medication.","Caregiver","Consider other OTC pain relief like Tylenol or Advil","provider","Resolve","","","","","",""],
    ["issue","%s has headache that is not relieved by Tylenol","Caregiver","So long as there is no fever, we may need to ride this one out.","provider","Resolve","","","","","",""],
    ["issue","Patient has inability to eat and continued weight loss","Caregiver","Let's keep an eye on the weight loss.","provider","Resolve","","","","","",""],
    ["issue","%s has more mouth sores appearing","Caregiver","There are several topical treatments you can try.  Please see http://www.emedicinehealth.com/canker_sores/article_em.htm","provider","Resolve","","","","","",""],
    ["issue","Patient has nasal congestion, drainage, cough","Caregiver","These may be signs of other infections.  Please see care plan on infections and monitor %s's temperature closely for any signs of fever.","provider","Resolve","","","","","",""],
    ["issue","Abnormally high dizziness and lightheadedness when standing,          ","Caregiver","Unfortunately this is normal, if it persists, let's bring it up as a talking point for next appointment","provider","Resolve","","","","","",""],
    ["issue","Noticing abnormal swelling at IV site","Caregiver","The visiting nurse looks to be visiting in the next 24 hours, I will instruct them to take a closer look at that region.","provider","Resolve","","","","","",""],
    ["issue","There's Redness at IV site","Caregiver","The visiting nurse looks to be visiting in the next 24 hours, I will instruct them to take a closer look at that region.","provider","Resolve","","","","","",""],
    ["issue","Bleeding gums","Caregiver","The visiting nurse looks to be visiting in the next 24 hours, I will instruct them to take a closer look at that region.","provider","Resolve","","","","","",""],
    ["issue","Fingernail color has been changing","Caregiver","The visiting nurse looks to be visiting in the next 24 hours, I will instruct them to take a closer look at that region.","provider","Resolve","","","","","",""],
    ["issue","Chronic itching","Caregiver","See care plan on skin conditions","provider","Resolve","","","","","",""],
    ["issue","Patient is complaining of consistent ringing in ears","Caregiver","See care plan on skin conditions","provider","Resolve","","","","","",""],
    ["HomeMonitoring","Patient weight has dropped over 10 lbs","Home Monitor","I scheduled a visit for the patient to come in this week","provider","Resolve","","","","","",""],
    ["HomeMonitoring","Patient has been vomiting more than 48 hours after treatment","Home Monitor","Unfortunately, this is normal for the treatment given, if it persists, we will need to adjust the anti nausea meds.","provider","Resolve","","","","","",""],
    ["HomeMonitoring","Patient has shortness of breath/chest pain","Home Monitor","Please come visit if the severity increases.","provider","Resolve","","","","","",""],
    ["HomeMonitoring","Patient has pain in a new place","Home Monitor","Patient called and discussed pain.  OTC Advil recommended","provider","Resolve","","","","","",""],
    ["HomeMonitoring","Patient has severe nausea","Home Monitor ","Patient switched to Anzemet ","provider","Resolve","","","","","",""],
    ["HomeMonitoring","Patient is experiencing hearing loss","Home Monitor","Patient instructed to come in or visit","provider","Resolve","","","","","",""],
    ["HomeMonitoring","Patient has not submitted daily measurements","Home Monitor","Call made to patient, contact made","provider","Resolve","","","","","",""],
    ["HomeMonitoring","Patient daily measurements incomplete","Home Monitor","Call made to patient, contact made","provider","Resolve","","","","","",""],
]