#[firstname,middlename,lastname,sex],[firstname,middlename,lastname,sex]
care_pair_arr = [
[["Pat","","Patient","f"],["Dorothy","","Day","f"]],
[["William","Husker","Adama","m"],["Lee","Apollo","Adama","m"]],
[["Kara","Starbuck","Thrace","f"],["Samuel","","Anders","m"]],
[["Sharon","Boomer","Valerii","f"],["Karl","Helo","Agathon","m"]],
[["Margaret","Racetrack","Edmonson","f"],["Brendan","HotDog","Costanza","m"]],
[["Gaius","","Baltar","m"],["D'Anna","","Biers","f"]],
[["Laura","","Roslin","f"],["Tory","","Foster","f"]],
[["Anastasia","","Dualla","f"],["Felix","","Gaeta","m"]],
[["Callie","","Tyrol","f"],["Galen","Chief","Tyrol","m"]],
[["Jean-luc","","Picard","m"],["William","Tiberius","Riker","m"]],
[["Deanna","","Troi","f"],["William","Tiberius","Riker","m"]],
[["Benjamin","","Sisko","m"],["Jake","","Sisko","m"]],
[["Joseph","","Sisko","m"],["Jake","","Sisko","m"]],
[["Jennifer","","Sisko","f"],["Jake","","Sisko","m"]],
[["Kassidy","","Yates","f"],["Jake","","Sisko","m"]],
[["Jadzia","","Dax","f"],["Ezri","", "Dax","f"]],
[["Curzon","","Dax","m"],["Ezri","", "Dax","f"]],
[["Torias","","Dax","m"],["Ezri","", "Dax","f"]],
[["Tobin","","Dax","m"],["Ezri","", "Dax","f"]],
[["Emony","","Dax","f"],["Ezri","", "Dax","f"]],
[["Joran","","Dax","f"],["Ezri","", "Dax","f"]],
[["Keiko","","O'Brien","f"],["Miles","","O'Brien","m"]],
[["Molly","","O'Brien","f"],["Miles","","O'Brien","m"]],
[["Ellen","","Tigh","f"],["Saul","","Tigh","m"]],
[["Kim","","Bauer","f"],["Jack","","Bauer","m"]],
]