#shuffled
DEMO_CASES=[
["Patient has fever higher than 101F'", 'Threshold alert from home monitoring device'],
['How long will the next visit last?', "it's a hectic day for her"],
["%s told me yesterday that it's really difficult to climb the stairs as she is completely winded after a few steps.  Is this normal?", 'ok, thanks.'],
['Patient is unable to afford food', 'the high calorie diet is hard to maintain'],
['Patient has pain in a new place', 'Seems worrisome'],
["Can other caregivers and loved ones be present at %s's next visit?", "I'm %s's ride,but also I'm the defacto translator"],
['Chronic itching', 'Been going on for a few days now'],
['Patient has painful or frequent urination', 'Alert from home monitoring device'],
['Patient is experiencing hearing loss', 'Very awkward conversations'],
['Will patient be able to drive by themselves to and from next visit?', 'We will need to sedate the patient.'],
['Will patient be able to drive by themselves to and from next visit?', 'The next visit will involve a strong chemo dosage, so the side effects will not be pleasant.'],
['Chronic itching', 'Has been getting progressively worse'],
['My skin is going crazy, help!', "it's red and rashed, but dry in other spots"],
['Patient has not submitted daily measurements', 'Missing data alert'],
['Patient has soreness', ' redness'],
['Patient has severe nausea', 'Severity: high, no vomiting'],
['%s has a runny nose', 'is it bad?'],
['Patient has irregular or rapid heart beat', 'Threshold alert from home monitoring device'],
['Swelling at IV site', 'What to do?'],
['How do I prevent recurring mouth sores?', 'been quite a nuisance'],
['%s keeps mentioning abnormal muscle weakness, anything more I can do?  ', "I know she's not exactly active, but she's not sedentary either."],
['How long will the next visit last?', 'I need to get back for another meeting that came up'],
['Patient is unable to afford food', 'She just lost her job'],
['HomeMonitoring', 'Patient has vomited 2 times in the past 24 hours'],
['Patient has inability to eat and continued weight loss', 'No vomiting per se, but no appetite'],
['Bleeding gums', 'Is it bad?'],
['Patient is concerned about rising pain in sternum', ' redness'],
['Patient has been vomiting more than 48 hours after treatment', 'Number of times: 3, has taken all anti emetics.'],
['not feeling well', '%s has been reporting severe nausea the past few days'],
['Patient daily measurements incomplete', 'Missing data alert'],
["How frequently should I be monitoring the patient's weight", 'I forget what the instructions were'],
['Bleeding gums', 'was about to brush my teeth when I saw it'],
['Patient is complaining of shaking chills', "It's been warm out"],
['Patient has nasal congestion', 'Any meds for this?'],
['Noticing abnormal swelling at IV site', "Haven't seen it yet, will do soon"],
['is it bad?', 'not sure if this is hives or a rash'],
['Patient is experiencing bleeding or bruising', 'Small aches do not seem to go away anymore'],
['Patient has not submitted daily measurements', 'Missing data alert'],
['Patient is experiencing hearing loss', 'Onset: 3 hours ago.  Partial hearing loss in left ear'],
['HomeMonitoring', 'Patient daily measurements incomplete'],
['more skin problems for %s', 'Thanks for the tip on the last skin issue!'],
['Patient has been vomiting more than 48 hours after treatment', 'Threshold alert from home monitoring device'],
['Irregular or rapid heart beat', "Has just happened, what's going on?"],
['When should the patient get vaccinated for H1N1?', 'Any word on availability?'],
['hi, regarding %s', '%s is reporting that they have not had a BM in over 2 days now.'],
['%s has severe diarrhea', '%s was up most of the night, was able to stay hydrated, but am worried.'],
['Patient has severe constipation or diarrhea', 'Alert from home monitoring device'],
['Patient has inability to eat and continued weight loss', 'Not feeling well'],
["How do I get patient's appetite back?", 'does not seem to be eating'],
['urgent', 'What order should I instruct the patient to take their anti nausea meds?'],
['Should I eat before next visit?', "I hear that there's some labs to be done, should I fast for those?"],
['more mouth sores appearing', 'Just happened last night'],
['Patient has pain that is not relieved by prescribed pain medication.', 'Not getting better'],
['%s seems to be rapidly losing weight', "I don't notice any altered diet"],
["There's Redness at IV site", 'not itchy though'],
['%s is complaining of shaking chills', "Just got off the phone and that's what she was saying, I'm stopping by later today, what should I look out for?"],
['When should the patient get vaccinated for H1N1?', 'The season approaches, when are vaccines available?'],
['Redness at IV site', 'What to do?'],
['Patient has headache that is not relieved by Tylenol', 'It keeps getting worse'],
['Patient is complaining of consistent ringing in ears', 'Been going on the past few days'],
['Should patient eat before next scheduled visit?', 'Is it a fasting visit?'],
['How do I prevent recurring mouth sores?', 'They seem to keep popping up and bothering her quite often.'],
['%s has nasal congestion, drainage, cough', "%s is feeling pretty miserable.  Hard to tell if there is any additional weakness since that's just the general feeling now."],
['Is oral chemotherapy taken by itself, or with other treatments?', 'Will food cause it to lose effectiveness?'],
["How do I get patient's appetite back?", "Just concerned that with the nausea and weakness, she'll lose even more weight."],
['Feeling rising pain in sternum', "I think it's the sternum, somewhere on my chest"],
['How much grace period is there for me to take my medicine around the scheduled time?', 'Are these things like antibiotiics and they need to be always in a certain schedule?'],
['Fingernail color has been changing', 'No pain though'],
['%s has severe constipation or diarrhea', 'Just happened today from what %s told me.'],
['Patient weight has dropped over 10 lbs', 'Daily reading reported.'],
['%s has headache that is not relieved by Tylenol', "It's a 7 on the scale of 1-10"],
['Patient has pain in a new place', 'Location: lower back'],
['Can other caregivers and loved ones be present at next visit?', 'Just wondering'],
['diarrhea?', "%s said it feels like it's happening but it is a normal movement - anything to help avoid?"],
['Will health insurance cover next round of prescriptions?', 'Will I run out of coverage?'],
['Patient has pain that is not relieved by prescribed pain medication.', "It's a 7 on the scale of 1-10"],
["I'm noticing %s has trouble hearing me, is this temporary?", "Is this part of the side effects?  I don't see it in the care plan"],
['Fingernail color has been changing', "Haven't seen it yet, will do soon"],
['Patient weight', "How frequently should I be monitoring the patient's weight"],
["%s is constantly complaining of nausea, doesn't she have meds for that?!", "Anything please, it's almost a daily occurrence."],
['Patient has shortness of breath/chest pain', 'Alert from home monitoring device'],
['Patient is complaining of consistent ringing in ears', 'Has been getting progressively worse'],
['Patient has more mouth sores appearing', 'Not getting better'],
['It hurts to go to the bathroom', 'please help'],
['Will health insurance cover next round of prescriptions?', 'Just concerned about the affordability'],
['Patient has soreness, redness, swelling, pus, or drainage at VAD site', 'Anything I can do to help?'],
['Patient has shortness of breath/chest pain', 'Onset: 12 hours ago'],
["Standard anti-nausea meds don't seem to help", ' anything else?'],
['help', 'Do I need to fast before my next visit?'],
['Patient has severe nausea', " and anti-nausea meds don't help"],
['fever', 'at what temperature should I know to call for help?'],
['Patient has blood in urine or stool', 'Threshold alert from home monitoring device'],
["I'm noticing %s seems to be rapidly gaining weight", "I don't notice any altered diet"],
['Bleeding or bruising', "I noticed the other day that on legs and arms it's pretty badly bruised"],
['Abnormally high dizziness and lightheadedness when standing', 'Pretty recent turn of events'],
['Abnormally high dizziness and lightheadedness when standing', 'Reported recently'],
['%s has red urine', "%s just called me, she's very worried."],

]